### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by samdark** [samdark/yiiframework-ru#10]
Показать старую доку по старым ссылкам (или редиректить с них), новую по новым.

**Comment by lavrentiev** [comment]
лучше сделать старую доку архивной и куда нибудь перенести. А новая пусть новой будет :) или разделить просто на версии.

**Comment by samdark** [comment]
Разделить — это и так понятно. Не будут же они вместе в одной куче. В архив рано потому как 1.1 всё ещё широко используется.

**Comment by samdark** [comment]
Вместо старой можно сделать редирект на yiiframework.com...

**Comment by rmrevin** [comment]
А в каком формате есть старая дока? Она генерируется?

**Comment by samdark** [comment]
Для старой сделал редирект.

**Comment by samdark** [comment]
Рецепты всё-равно придётся рендерить...

**Comment by samdark** [comment]
https://github.com/samdark/yiiframework_ru_cookbook

**Comment by lavrentiev** [comment]
Так если убирать документацию на yii зачем оставлять рецепты для ние?

**Comment by samdark** [comment]
Она не убирается, делается редирект на её копию на yiiframework.com. Кукбука по 1.1 там нет.
