### ISSUE TITLE
Импорт новостей с yiiframework.ru

### ISSUE THREAD

**Issue by samdark** [samdark/yiiframework-ru#11]
Консольный контроллер, позволяющий забрать новости из старой базы.

**Comment by samdark** [comment]
Или просто дамп...

**Comment by Sassoft** [comment]
@samdark , хотелось бы реализовать эту идею.
Какая структура старой базы сайта была?
И как планируется забирать ? просто дампануть таблицу старых новостей и потом через консоль преобразовать данные в новую структуру?

**Comment by samdark** [comment]
Да. Одноразовая консольная команда.

**Comment by samdark** [comment]
[yiiframework_ru_2015-12-24.sql.gz](https://github.com/samdark/yiiframework-ru/files/71666/yiiframework_ru_2015-12-24.sql.gz)

**Comment by Sassoft** [comment]
Как я вижу в старом дампе были поля:
 id, title, content, contentDisplay, contentBeforeCut, createdOn,alias
В новом Post:
id, title, body, link, user_id, status, created_at, updated_at

Связь:
body->content
link->alias
created_at -> createdOn
status -> тут STATUS_ACTIVE?

user_id, что с ним?

**Comment by samdark** [comment]
Новости постил только я :)

**Comment by samdark** [comment]
В старом контент оформлен в markdown extra. В новом планируется GitHub-flavored markdown. Основное отличие — блоки кода:

```
  ~~~
  [php]
  ~~~

  ```php
  ```
```

**Comment by Sassoft** [comment]
И кстати еще вопрос, дамп таблицы тоже имеет Post имя.. Они конфликтовать будут тогда.
Или в дампе имя таблицы потом заменишь на другое при выгрузке?

**Comment by samdark** [comment]
Старое в другой базе.

**Comment by Sassoft** [comment]
Куда лучше положить конфиг от старой базы? ведь по сути он нужен будет только раз..
или как параметры консольной команды принимать?

**Comment by samdark** [comment]
Как параметры имя базы, логин, пароль.
