### ISSUE TITLE
Не выходит подтвердить почту

### ISSUE THREAD

**Issue by samdark** [samdark/yiiframework-ru#117]

**Comment by samdark** [comment]
Там есть запрос на подтверждение почты.

**Comment by gud3** [comment]
Да есть, но ссылка для подтверждения будет показана после того как пройдёт время с момента последней отправки + `Yii::$app->params['user.resendVerified']`

**Comment by samdark** [comment]
Да, надо поправить это дело... я недавно реализовал подтверждение для yiiframework.com нового. Оно немного проще и работает точно: https://github.com/yiisoft-contrib/yiiframework.com/blob/master/controllers/AuthController.php#L226
