### ISSUE TITLE
Нерабочая ссылка в документации

### ISSUE THREAD

**Issue by Pchol** [samdark/yiiframework-ru#118]
На странице http://yiiframework.ru/doc/cookbook/ru/form.validation.reference внизу есть ссылка "Работа с формами → Создание модели", которая ведет на несуществующую страницу.

**Comment by samdark** [comment]
Поправил: https://github.com/samdark/yiiframework_ru_cookbook/commit/81d6a8523ba2b1a473c817af53baaf03acee31f9
