### ISSUE TITLE
Получение последней версии фреймворка с github и её отображение

### ISSUE THREAD

**Issue by samdark** [samdark/yiiframework-ru#12]

**Comment by githubjeka** [comment]
варианты получения:
- через консольное приложение, дерганье API
- может есть возможность настроить webhooks ?

**Comment by samdark** [comment]
Есть возможность, да.

**Comment by githubjeka** [comment]
Здорово, тогда создам входной контроллер.
А где хранить лучше - в БД ?

**Comment by samdark** [comment]
Да.

**Comment by samdark** [comment]
Предлагаю для этих целей сделать табличку:

```
variable
----------
key
value
```

**Comment by samdark** [comment]
Как альтернатива — хранить в PHP-массиве аля конфиг `versions.php`. Возможно, это даже лучше:

```php
<?php
return [
    'yii1-version' => '1.0.6',
    'yii2-version' => '2.0.6',
   // ...
];
```
