### ISSUE TITLE
Баг верстки

### ISSUE THREAD

**Issue by fourclub** [samdark/yiiframework-ru#122]
если перейти в пост, например: http://yiiframework.ru/news/174/debug-2010
и прокрутить страницу колесиком мышки вниз и обратно вверх, то, панель, в которой указывается заголовок (в данном случае: Debug 2.0.10) налазиет на текст: Дата публикации: 04.09.17 10:25| Автор: samdark

**Comment by githubjeka** [comment]
![image](https://user-images.githubusercontent.com/874234/30034658-6d067e06-91ab-11e7-9061-21dbc828d60d.png)

**Comment by Carsak** [comment]
Не могу воспроизвести.
Chrome 60+
http://joxi.ru/LmG7BMPHe8ke0m

При каком разрешении налазит хедер?

**Comment by fourclub** [comment]
win 10 - 1920x1080
Google Chrome Версия 61.0.3163.100 (64 бит)

Если скролом мышки помотать вверх вниз кучку раз то такая хрень появится.

**Comment by sokoji** [comment]
Это происходит из-за того, что у текста задан transition и при резком скролле вверх скрипт стики не успевает пересчитать высоту корректно и задаёт блоку меньшую высоту, чем фактическая.  Один из вариантов решения — это уменьшить немного транзишн и задать setTimeout для пересчёта высоты блока в скрипте стики:

```
setTimeout(function() {
   s.stickyWrapper.css('height', s.stickyElement.outerHeight()); 
}, 200);
```

Вообще решение мне не очень нравится, но пока что не смог придумать ничего лучше. Можно ещё пробовать запоминать начальную высоту блока при инициализации страницы, когда заголовок крупный и задавать именную эту высоту.

Что думаете?

**Comment by samdark** [comment]
Лучше исправить так, чем никак...
