### ISSUE TITLE
Прописать в футере ссылку на репозитории сайта

### ISSUE THREAD

**Issue by Carsak** [samdark/yiiframework-ru#125]
Предлагаю где то на сайте, например в футере, оставить ссылку на репозиторий
https://github.com/samdark/yiiframework-ru

Зачем это надо?
Это может привлечь больше контрбьютеров для помощи сайту. Новичкам будет легче найти ссылку на репу, да и по СЕО будет полезно. 

Также пришла идея.
Сделать кнопку или ссылку с текстом "Нашли ошибку? Создайте тикет на Гитхабе." И редиректит на страницу https://github.com/samdark/yiiframework-ru/issues/new
Возможно нужно будет сделать шаблон для новых тикетов. Если идея жива, то можно создать новую задачу

**Comment by samdark** [comment]
Согласен.

**Comment by Carsak** [comment]
Оказывается в футере уже есть ссылка на "Сообщить об ошибке"
![image](https://user-images.githubusercontent.com/9497934/31528136-7d2cc04a-aff3-11e7-8a49-f8421ee382b5.png)

Не заметил
