### ISSUE TITLE
Ошибка symlink(): Cannot create symlink, error code(1314)

### ISSUE THREAD

**Issue by Carsak** [samdark/yiiframework-ru#126]
При первом запуске сайта появляется ошибка:
symlink(): Cannot create symlink, error code(1314)
http://joxi.ru/p27gBPNuoR1nE2
![image](https://user-images.githubusercontent.com/9497934/31376493-f872af1e-adc6-11e7-964a-601d2b8fa944.png)

Шаги воспроизведения:
Работать в  Windows 10 & openserver > 5.22
Сделать шаги 1, 2, 3 в readme
Запустить сайт.
Увидеть ошибку

**Comment by samdark** [comment]
Да, симлинки Windows без админского доступа создавать нормально не умеет.
