### ISSUE TITLE
Главная страница со списком новостей

### ISSUE THREAD

**Issue by lav45** [samdark/yiiframework-ru#134]
Предлагаю использовать `http://yiiframework.ru/news`
т.к. страница новостей `http://yiiframework.ru/news/190/jqueryui-207`

**Comment by samdark** [comment]
?

**Comment by lav45** [comment]
К примеру, есть страница с новостью http://yiiframework.ru/news/190/jqueryui-207, но с неё нельзя перейти на страницу со списком новостей. Предположил что http://yiiframework.ru/news и будет страница со списком всех новостей.
Но оказалось что ошибся
```php
'news/<page:\d+>' => 'post/index',
```
https://github.com/samdark/yiiframework-ru/blob/master/config/system/urls.php#L9

Судя по [PostController::actionIndex()](https://github.com/samdark/yiiframework-ru/blob/master/controllers/PostController.php#L73) `page` не является обязательным параметром и его можно без проблем убрать из роутига
```php
'news' => 'post/index',
```

**Comment by samdark** [comment]
Поправил.
