### ISSUE TITLE
Ошибка входа через twitter

### ISSUE THREAD

**Issue by SergeKuznetsov** [samdark/yiiframework-ru#136]
При попытке войти через twitter: "Возникла внутренняя ошибка сервера."
- учетная запись на yiiframework.ru уже есть (с почтой)
- twitter не привязан

**Comment by samdark** [comment]
Попробуйте ещё раз.

**Comment by samdark** [comment]
Префикс www запретил. Сделал редирект. Twitter и Facebook проверил. Нормально работают оба. Может вы запретили твиттеру отдавать email?

**Comment by SergeKuznetsov** [comment]
twitter'у разрешал отдавать email. у меня на проекте (с yii2-authclient) работает twitter.
Хотел только что еще раз проверить: но на странице https://yiiframework.ru/site/login теперь вообще не вижу социальных кнопок.
![image](https://user-images.githubusercontent.com/1486163/39566054-e48fe262-4ec2-11e8-818a-dd5c758e3eec.png)

**Comment by samdark** [comment]
Поправил.
