### ISSUE TITLE
Trying to install on c9.io

### ISSUE THREAD

**Issue by hdushku** [samdark/yiiframework-ru#137]
Have been trying to install on c9.io but only the homepage displayed, when I try to access /users shows

Not Found
The requested URL /users was not found on this server.

Configured the Apache using command:
sudo vi /etc/apache2/sites-enabled/001-cloud9.conf

but no success

**Comment by samdark** [comment]
You need `.htaccess`. Since we're running with nginx, it's not needed but https://www.yiiframework.com/doc/guide/2.0/en/start-installation#recommended-apache-configuration
