### ISSUE TITLE
How to alignment img in html 

### ISSUE THREAD

**Issue by Vlaz2** [samdark/yiiframework-ru#148]
Hi.
Please help me find out how alignment img with different height and width in html code.
This is suppost to be some container or i don't know
Thanks for try

**Comment by githubjeka** [comment]
Может стоит обратиться в службу поддержки, для выяснения, откуда прилетают такие issues?

![image](https://user-images.githubusercontent.com/874234/80206412-e8c70580-8634-11ea-8195-817eeaa47950.png)

**Comment by samdark** [comment]
Я уже.
