### ISSUE TITLE
Битые ссылки на восстановление пароля и FAQ при регистрации нового пользователя форума

### ISSUE THREAD

**Issue by execut** [samdark/yiiframework-ru#156]
На [странице регистрации форума](https://yiiframework.ru/forum/ucp.php?mode=login&redirect=ucp.php%3Fmode%3Dregister) неправильные ссылки:
[Восстановить пароль](https://yiiframework.ru/forum/user/forgot_password) и [FAQ](https://yiiframework.ru/forum/help/faq)

Обе ведут на 404 страницы

**Comment by samdark** [comment]
Исправил. Спасибо.

**Comment by execut** [comment]
Пожалуйста

**Comment by execut** [comment]
Проверил, заработало
