### ISSUE TITLE
Does anyone know how to create vertical carousel javascript?

### ISSUE THREAD

**Issue by Marik2k4** [samdark/yiiframework-ru#160]
I have found code from "CodePen" named "vanilla js carousel" (https://codepen.io/ekeric13/pen/wKOwmg). But I can't figure out how to create vertical infinite carousel. If you already have code, I wish you would share it with me.

P.S: I don't want to use any plugins or libraries.

**Comment by samdark** [comment]
This isn't a forum.

**Comment by githubjeka** [comment]
Всё же интересно, откуда прилетают эти сообщения?
Поддержка GitHub ничего не ответила по этому поводу?

**Comment by samdark** [comment]
Нет.

**Comment by githubjeka** [comment]
В то время как это началось, у нас был Gitter , может оттуда ....

**Comment by Marik2k4** [comment]
> В то время как это началось, у нас был Gitter , может оттуда ....

Я просто гуглил, можно ли задать вопрос на гит хаб, и мне эта ссылочка вылезла
