### ISSUE TITLE
Некорректный формат RSS

### ISSUE THREAD

**Issue by lvb3q** [samdark/yiiframework-ru#170]
Не удается подписаться на ленту новостей в Mozilla Thunderbird, говорит: «Формат ленты новостей является некорректным».

[Feed Validation Service](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fyiiframework.ru%2Frss)

**Comment by samdark** [comment]
Нужно вот тут https://github.com/samdark/yiiframework-ru/blob/master/controllers/PostController.php#L215 зафорсить HTTPS. Если есть чуть времени, pull request бы не помешал.
