### ISSUE TITLE
Настройка RBAC

### ISSUE THREAD

**Issue by githubjeka** [samdark/yiiframework-ru#18]
Можно заюзать https://github.com/githubjeka/gui-rbac-yii2

**Comment by samdark** [comment]
У нас роли простые-простые. Можно консольный контроллер сделать, который один раз их поднимет + серию команд для управления. Типа такого: https://github.com/samdark/yiifeed/blob/master/commands/RbacController.php

Но можно и GUI, конечно...

**Comment by githubjeka** [comment]
Да я за консольный первоначально. С gui повременим тогда.

**Comment by rmrevin** [comment]
@samdark подскажи, как идиологически правильно обновлять и расширять права в случае консольной команды?

**Comment by samdark** [comment]
Также, как и в случае GUI. Миграциями.

**Comment by rmrevin** [comment]
То есть первая инициализация происходит в консольной команде, а обновления в миграциях?

**Comment by samdark** [comment]
Не, инициализацию тоже лучше делать в миграциях.

**Comment by githubjeka** [comment]
А если rbac в файлах хранится, то миграции и не нужны.

**Comment by githubjeka** [comment]
А ещё можно переписать DbManager, чтобы он при внесении в таблицы создавал файлы миграций :)

**Comment by Carsak** [comment]
Парни. А какие роли на сайте будут?
Предположения:
1. Админ.
2. Модератор постов
3. Простой пользователь.

**Comment by Carsak** [comment]
А почему бы не назначать роль через CRUD юзеров? Будет колонка, где можно будет выбрать роль из dropdown?

**Comment by githubjeka** [comment]
1. Админ. 2. Модератор постов 3. Простой пользователь. - для начала сгодиться.

**Comment by samdark** [comment]
@Carsak потому что хранить роль в таблице юзера — это неправильно.

**Comment by githubjeka** [comment]
... если это роль относится к rbac. А если она выступает как тип пользователя - то хранить можно.

**Comment by Carsak** [comment]
@githubjeka А разве тип пользователя и роль(Role) не одно и тоже?

**Comment by samdark** [comment]
@githubjeka а зачем нам ещё и тип?

**Comment by githubjeka** [comment]
это я о своём - личном :)

**Comment by githubjeka** [comment]
@Carsak всё это излишне, можно проверять `Yii::$app->user->can('isAdmin')`
Ролей у пользователя может быть много.

**Comment by Carsak** [comment]
@githubjeka Значит будем использовать встроенный RBAC YII2?

**Comment by samdark** [comment]
Да.
