### ISSUE TITLE
Переделка формы frontend/models/User с AR на Model

### ISSUE THREAD

**Issue by githubjeka** [samdark/yiiframework-ru#20]
Лучше сделать от extends \yii\base\Model

https://github.com/samdark/yiiframework-ru/blob/development/frontend/models/User.php

**Comment by samdark** [comment]
Да, можно и так.

**Comment by rmrevin** [comment]
Эта модель используется и в контроллере.
Не забудьте в контроллере класс заменить.
https://github.com/samdark/yiiframework-ru/blob/development/frontend%2Fcontrollers%2FProfileController.php
