### ISSUE TITLE
Раздел QA

### ISSUE THREAD

**Issue by githubjeka** [samdark/yiiframework-ru#23]
Есть готовый модуль QA - https://github.com/artkost/yii2-qa

Вроде нормальный и многое реализовано. В нём уже найдены баги и можно помочь их исправить, но вот дилема - как этот модуль использовать тут?

Вдруг понадобится что-то переделать, нужно ждать пока там смержат. 
Как поступить? Делать форк и юзать его или сразу копировать в `/app/modules/` и вести всю разработку отдельно от первоначального?

UPD:
- [x] CRUD
- [x] comments for Q&A
- [x] метки для вопросов (tags)
- [ ] реализация счётчиков (голоса, ответы, просмотры)
- [ ] дизайн

**Comment by samdark** [comment]
Посмотрел на схему. Там нет индексов и внешних ключей. Подозреваю, чуть нагрузки и оно не выдержит...

**Comment by githubjeka** [comment]
А в остальном? Своё делать или брать этот и допиливать под свои нужды?

**Comment by samdark** [comment]
В остальном модуль не универсальный. Не вижу смысла в нём именно как в модуле... я бы скопировал и сделал частью приложения. Или даже сделал свою миграцию с нормальными индексами и потом поправил бы остальное.

**Comment by githubjeka** [comment]
Создал примитивные модели.
https://github.com/samdark/yiiframework-ru/commit/bdd1c932934f0297afca46e68679ea35b1b759e1

**Comment by lavrentiev** [comment]
Лучше свое :(

**Comment by githubjeka** [comment]
А чего смайл грустный? Уже запулил ветку - можно пробовать и допиливать.

**Comment by lavrentiev** [comment]
Это как у тостера можно придумать типа вклад и т.д

**Comment by githubjeka** [comment]
Теги прикрутил.
Теги создаются в backend, в frontend прикрепляются к вопросу. Можно выбрать пока не ограниченное количество.

**На обсуждение:**

- Сейчас есть parent tags и child tags, вешать на вопрос можно и те и другие, или стоит сделать, чтобы только child tags можно было выбирать?
- Какое количество тегов можно вешать на вопрос? (Пока не ограничено)

**Comment by samdark** [comment]
> Сейчас есть parent tags и child tags, вешать на вопрос можно и те и другие, или стоит сделать, чтобы только child tags можно было выбирать?

Любые.

> Какое количество тегов можно вешать на вопрос? (Пока не ограничено)

5

**Comment by samdark** [comment]
Кстати, https://github.com/creocoder/yii2-taggable — очень хорошая штука.

**Comment by JiLiZART** [comment]
Очень хочу чтобы мой модуль https://github.com/artkost/yii2-qa был очень полезен, насколько реально сделать кастомизацию, чтобы он был расширяем. Просто хочется избавится от повторяющегося кода, и внести вклад в сообщество.

**Comment by samdark** [comment]
Ну, надо довести dev-ветку до стабильного состояния. А там посмотрим.

**Comment by samdark** [comment]
Так-то мы уже начали примерно то же...

**Comment by githubjeka** [comment]
Переоткрыто тут https://github.com/samdark/yiiframework-ru/issues/30
