### ISSUE TITLE
Раздел: Вопросы и ответы (new)

### ISSUE THREAD

**Issue by lavrentiev** [samdark/yiiframework-ru#30]
Раздел: Вопросы и ответы (new)
- Основной раздел
  - [x] Блок с выводом тегов в right-sidebare 
  - [x] Возможность отображать свои вопросы во вкладке
  - [x] Возможность отображать решенные вопросы во вкладке
  - [x] Возможность отображать вопросы без ответа во вкладке
  - [ ] Возможность отображать избранные вопросы во вкладке
  - [x] Возможность сортировки
    - [x] по дате
    - [x] по просмотрам
    - [x] по подписчикам
  - [x] Представление вопроса в основном разделе
    - [x] Заголовок вопроса
    - [x] Имя автора вопроса
    - [x] Дата добавления вопроса
    - [x] Краткое описание вопроса (кол-во символов < 300)
    - [x] Информационные пункты
      - [x] Кол-во просмотров 
      - [x] Кол-во ответов 
      - [x] Кол-во отслеживающих вопрос
- Просмотр вопроса
  - [ ] Блок с выводом похожих вопросов в right-sidebare
  - [x] Представление вопроса при просмотре
    - [x] Заголовок вопроса
    - [x] Имя автора вопроса
    - [x] Изображения пользователя (gravatar)
    - [x] Кнопка редактирования вопроса
    - [x] Дата добавления вопроса
    - [x] Краткое описание вопроса (кол-во символов < 300)
    - [x] Информационные пункты
      - [x] Кол-во просмотров 
      - [x] Кол-во ответов 
      - [x] Кол-во отслеживающих вопрос 
    - [ ] Возможность комментировать вопрос
    - [x] Возможность писать ответ на вопрос
    - [ ] Возможность комментировать ответ на вопрос
  - [ ] Представление комментария
    - [ ] Имя автора комментария
    - [ ] Дата добавления комментария
    - [ ] Текст комментария
    - [ ] Редактирование комментария
  - [x] Представление ответа на вопрос
    - [x] Имя автора ответа
    - [x] Изображения пользователя (gravatar)
    - [x] Дата добавления ответа
    - [x] Текст ответа
    - [x] Редактирование ответа
- Автор вопроса может выбирать варианты решения только ответы.
- Максимальное кол-во тегов к вопросу **5** 
- Каждый пользователь может добавлять вопрос к себе в избранное.
- Удаления вопроса, ответа, комментария (невозможно), авторам доступно только редактирование.

**Если есть предложения дополнительно жду!**

**Comment by loveorigami** [comment]
```
Удаления вопроса, ответа, комментария (невозможно), авторам доступно только редактирование.
```
Я бы дополнил.
* Редактировать можно в течение определенного времени (2 часа)
* Редактировать можно, если на него не было ответов.

------
Много раз сталкивался, когда пишут комментарий, провоцируют на ответы, а потом, отредактировав, оставляют "-------------" или "del"

**Comment by lavrentiev** [comment]
Возник вопрос, @githubjeka это точно надо " Возможность выделять последний новый добавленный вопрос"?

**Comment by githubjeka** [comment]
Откуда это? Что это значит?

**Comment by samdark** [comment]
Нет, это не надо.

**Comment by lavrentiev** [comment]
@samdark ок, @githubjeka ты просто тока в гиттере писал что надо замутить это (как тут http://eshill.ru/yii/questions.html )

**Comment by githubjeka** [comment]
А, это было закрепление вопросов в шапке..ну ок, пока реализацию можно отложить...

**Comment by samdark** [comment]
Эм... не, ну вопрос, понятное дело, в шапке всегда.

**Comment by samdark** [comment]
@githubjeka возможность админу закрепить какой-то один вопрос в шапке? Или чего это?

**Comment by githubjeka** [comment]
да

**Comment by lavrentiev** [comment]
а смысл в этом есть?

**Comment by samdark** [comment]
Да не особо. Разве что деньги за это брать, но этого в планах нет.

**Comment by lavrentiev** [comment]
@samdark "Блок с выводом похожих вопросов в right-sidebare" а это я как понимаю в конце когда будет подключен уже Sphinx?

**Comment by samdark** [comment]
Не думаю, что сфинкс тут особо поможет.

**Comment by samdark** [comment]
Хотя мб и поможет.

**Comment by samdark** [comment]
Это можно пока оставить без реализации и доделать после запуска.

**Comment by lavrentiev** [comment]
кк

**Comment by rugabarbo** [comment]
Почему нельзя просто использовать SO?

Например, разработчики Symfony решили полностью отказаться от форума и собственных велосипедов в пользу SO: http://symfony.com/blog/symfony-support-stack-overflow-as-the-main-medium

Для русскоязычного сообщества можно использовать http://ru.stackoverflow.com

Какой уникальный функционал будет в локальном разделе "Вопросы и ответы" по сравнению с функционалом SO?

**Comment by samdark** [comment]
По сути, никакого...

**Comment by rugabarbo** [comment]
Понаблюдал за русскоязычным SO с тегом yii2: https://ru.stackoverflow.com/questions/tagged/yii2

Не сказать, что там какая-то серьёзная активность. По ощущениям на форуме активность в разы выше.

Исходя из этого, считаю, что создание самописного раздела "Вопросы и ответы" - пустая трата времени. Не будет востребовано.

**Comment by samdark** [comment]
А если понаблюдать за "тостером"?

**Comment by rugabarbo** [comment]
На тостере не разделены **yii1** и **yii2**. Есть лишь общий тэг **yii**, по которому за всё время его существования задано около 4к вопросов: https://toster.ru/tag/yii/questions - и динамика тоже не очень высокая. 1-2 вопроса в день...

**Comment by alexraputa** [comment]
@rugabarbo, как это нету по Yii 2, а это что [Yii 2](https://toster.ru/tag/yii2/questions)? За последний день 8 вопросов по тегу Yii 2.

**Comment by rmrevin** [comment]
Прибавим к этому чаты из гиттера, телеграма (возможно и др месенджеров), группы в фб\вк, форум. И вот уже мы получили порядочный трафик, который размыт по разным каналам. Большинство из которых не индексируется. Разде В/О (внутренний или на so) имеет смысл, если кто-то сможет консалидировать этот трафик.

**Comment by rmrevin** [comment]
Кстати, есть ещё такая категория людей, которые в силу своей интровертности боятся\стесняются задавать вопросы. Можно как гипотезу рассмотреть возможность анонимных вопросов (клуб анонимных программистов). :-)

**Comment by rugabarbo** [comment]
@alexraputa спасибо, не нашёл его сразу. Вижу, что под тэгом yii2 тоже мало вопросов.

**Comment by rugabarbo** [comment]
@rmrevin мне кажется, масса инертна и разом не пересядет с гиттера, FB, SO и прочих ресов на новый ресурс. При этом новый ресурс должен быть выше по качеству (конкурентность), чтобы это начало происходить. Процесс затяжной. Неясно, кто будет создавать и поддерживать высокое качество этого раздела на yiiframework.ru 

Видится, что нужны большие ресурсы (человеческие, а после получения большого трафика и технические), чтобы консолидировать весь этот трафик с годами. Мне кажется, в OpenSource-разработке таких ресурсов не найти.

**Comment by rmrevin** [comment]
@rugabarbo тут вопрос доверия с одной стороны (для вопрошающих) и мотивации с другой стороны (для отвечающих). Этот новый раздел, можно сказать, является официальным (т.к. размещён на сайте российского "представительства" фреймворка). Если мы сможем обеспечить качественные консультации именно в этом канале, то вопрос трафика постепенно разрешится. Новичкам не придётся выдумывать, куда же задать вопрос - so, ru.so, тостет, гиттер, issues на гитхабе (есть и такие), канал в тг и тд. Он будет знать, что на оф сайте yii он может задать любой вопрос и получить ответ.
Но при этом с другой стороны наша задача дать мотивацию для того, чтобы специлисты отвечали на эти вопросы. Тут сложнее. На ум приходит только классическая система рейтинга, но не всем нужны красивые циферки в профиле. Можно поразмыслить на тему доп услуг за "карму". Типа твоё резюме\расширение будет выше в рейтинге. Или, например, сделать раздел для "заказа" ревью твоего опенсёрс решения.
Также есть вариант "карму" заменить на донат "на пиво". Я думаю это более мощная мотивация уделить хотя бы пару часов в неделю этому разделу. Но вопрос в том, будут ли люди донатить.
Это всё поверхностные мысли, прошу не расценивать как конкретное законченное предложение.

**Comment by Tolembek** [comment]
Здравствуйте! Загружаю через такой виджет use dosamigos\fileupload\FileUploadUI; картинки
Когда выбираю картинку и нажимаю кнопку открыть сразу загружается картинка, как задать размер картинке ?
как видите скрине снизу загружаемая картинка загружается по умолчанию (то есть берет свой размер)
А после обновление страницы я уже задал размер (Это видно на последней картинке)
свойство previewMaxWidth не работает или это не то что мне нужно

echo FileUploadUI::widget([
'model' => $filess,
'attribute' => 'pathFile',
'url' => ['addproduct/upload', 'id' => $model->id, 'class' => 'Addproduct'],//, 'id' => Yii::$app->user->getIdentity()->id
'gallery' => false,
// 'load' => false,
'formView' => '@app/views/addproduct/upload.php',
'fieldOptions' => [
'accept' => '/(\.|\/)(gif|jpe?g|png)$/i'
],
'clientOptions' => [
'imageMaxWidth' => 200,
'previewMaxWidth' => 20,
'previewMaxHeight' => 20,
'maxNumberOfFiles' => 1,
/*'disableImageResize'=>" /Android(?!.*Chrome)|Opera/ .test(window.navigator && navigator.userAgent)",
"imageMaxWidth"=> 800,
"imageMaxHeight"=> 800,*/
"imageCrop" => false, // Force cropped images

'autoUpload' => 'true',
'limitMultiFileUploads' => Yii::$app->params['uploadFile']['maxupload'], //4 file upload maximum
'limitMultiFileUploadSize' => Yii::$app->params['uploadFile']['maxuploadbyte'], //4MB
//'acceptFileTypes'=>'/(\.|\/)(gif|jpe?g|png|doc|docx|xls|xlsx|ppt|pptx|txt|doc|rtf|pps|pdf|bmp|tif)$/i',
'maxFileSize' => Yii::$app->params['uploadFile']['maxuploadbyte'], // 4 MB
'maxNumberOfFiles' => Yii::$app->params['uploadFile']['maxupload'] // 4 MB
],
'clientEvents' => [
'fileuploadadd ' => 'function(e, data) {
var width = 100;
console.log(e);
console.log(data);
}',
],
]);

**Comment by samdark** [comment]
Думаю, на сегодня достаточно мест чтобы не пилить ещё одно с Q&A.

**Comment by demitep** [comment]
Здравствуйте, у меня проблема с TensorFlow 1.14.0 на ubuntu 19.04. 
**Ошибка:**
Using TensorFlow backend.
Недопустимая инструкция (стек памяти сброшен на диск).

**Версии по:**
x84_64,
pip 19.2.3,
python3.7.
Не подскажете, что делать? И если я написал не туда, куда нужно, то подскажите пожалуйста, куда писать?

**Comment by Chechenec01** [comment]
как добавить русский кириллический шрифт в игру? например в dynasty warriors 9 empires.
