### ISSUE TITLE
PHP Notice – yii\base\ErrorException  Trying to get property of non-object

### ISSUE THREAD

**Issue by githubjeka** [samdark/yiiframework-ru#36]
in [`frontend/views/qa/_formAnswer.php`](https://github.com/samdark/yiiframework-ru/blob/development/frontend/views/qa/_formAnswer.php#L21)

Связано с https://github.com/samdark/yiiframework-ru/pull/32#discussion-diff-47816981

**Comment by samdark** [comment]
@lavrentiev обещал заняться.

**Comment by JiLiZART** [comment]
```Yii::t('qa', !$answerForm->answer->question_id ? 'Post Your Answer' : 'Update Your Answer')```
нужно превратить в 
```!$answerForm->answer->question_id ? Yii::t('qa', 'Post Your Answer') : Yii::t('qa',  'Update Your Answer')``` иначе yii message просто не найдет

**Comment by lavrentiev** [comment]
Все находит!

**Comment by JiLiZART** [comment]
@lavrentiev и файлы правильные генерит? со строками 'Post Your Answer' и 'Update Your Answer' ,

**Comment by lavrentiev** [comment]
Да все норм.

**Comment by samdark** [comment]
@githubjeka поясни, что нужно.

**Comment by githubjeka** [comment]
[Тут](https://github.com/samdark/yiiframework-ru/blob/development/frontend/controllers/QaController.php#L117) создаётся QuestionAnswerForm

[здесь](https://github.com/samdark/yiiframework-ru/blob/development/frontend/views/qa/_formAnswer.php#L21) PHP Notice срабатывает на этой форме, так как `answer = null`

И проверка при инициализации не корректная:
https://github.com/samdark/yiiframework-ru/blob/development/frontend/models/QuestionAnswerForm.php#L34
