### ISSUE TITLE
Необходима JS реализация обработки результата добавление вопроса в избранное

### ISSUE THREAD

**Issue by githubjeka** [samdark/yiiframework-ru#37]
Контроллер - https://github.com/samdark/yiiframework-ru/blob/6877c121f88f00a27be8d86b2e3a34782aa5ea66/frontend/controllers/QaController.php#L244ъ

Кнопка - https://github.com/samdark/yiiframework-ru/blob/development/frontend/widgets/qa/views/favorite.php#L8

**Comment by Carsak** [comment]
Могли бы объяснить непосвященным более подробно.

**Comment by githubjeka** [comment]
нажимаем на кнопку и сердечко загорается, без перезагрузки страницы. Ещё раз нажимаем убирается вопрос из избранного, сердечко становится обычным, опять же без перезагрузки страницы.

**Comment by lavrentiev** [comment]
#65 сделали же, закрывайте
