### ISSUE TITLE
Новости / статьи

### ISSUE THREAD

**Issue by samdark** [samdark/yiiframework-ru#4]

**Comment by rmrevin** [comment]
Как предполагается реализовывать работу с новостями?
Возможно стоит всё таки делать раздел администрирования, для управления новостями?

**Comment by samdark** [comment]
Что-то вроде yiifeed: https://github.com/samdark/yiifeed

**Comment by samdark** [comment]
То есть это сборная солянка всего, а не только официальные анонсы. Добавлять может кто угодно, но нужна премодерация (за исключением проверенных юзеров).

**Comment by samdark** [comment]
Формат — markdown, github flavor.

**Comment by rmrevin** [comment]
Я это веду к тому, что админка всё же нужна. Для той же модерации. Значит basic app не прокатит.

**Comment by samdark** [comment]
Ну ОК, пусть будет advanced.

**Comment by rmrevin** [comment]
Я предлагаю взять мой допиленый каркас.
https://github.com/cookyii
Мы используем этот каркас во всех наших проектах.
Тут уже готовый лэйаут для админки на adminlte + angularjs
И есть несколько готовых общих модулей (сейчас готовы управление юзерами, страницами, почтовыми шаблонами, отправленными письмами, и на подходе авторизация\регистрация\восстановление пароля во фронте)

Код yiigist также опирается на этот каркас и использует библиотеки из набора cookyii.

**Comment by rmrevin** [comment]
п.с. на этом каркасе наша команда построила уже около 10-15 проектов (в основном crm и erp системы)

**Comment by samdark** [comment]
ОК. Пусть будет.

**Comment by samdark** [comment]
Посмотрел, что-то навёрнуто там неслабо... не уверен, что всё оно нам надо.

**Comment by githubjeka** [comment]
Я тоже сижу и думаю про это
Но с нуля тоже не вариант делать...

**Comment by samdark** [comment]
@rmrevin какой из репозиториев каркас?

**Comment by samdark** [comment]
А, https://github.com/cookyii/project.

**Comment by samdark** [comment]
Думаю, стартанём с advanced...

**Comment by rmrevin** [comment]
Конечно. Это девелоперская версия. Всё лишнее убирается. Это тот же адванс, только адптированный под автодеплой и с готовым ворфлоу по созданию модулей.

**Comment by samdark** [comment]
Мне не нравится: `composer global require "cookyii/build:dev-master"`

**Comment by samdark** [comment]
А также `.env`. yiiframework.ru хостится не на отдельном сервере. Окружение общее на тучу проектов.

**Comment by samdark** [comment]
Хотя мб я не присмотрелся. Если уверен, что с этим всем не будет проблем, заливай в репку начальный темплейт.

**Comment by rmrevin** [comment]
Глобально пакет cookyii/build уже не нужно устанавливать.
Про `.env` не совсем понял. Можно хранить копии `.env` для разных окружений в репе. Просто это файл специально для хранения паролей и токенов доступа. Эта информация не должна храниться в гите (тем более опен сёрсном).

По поводу тестирования, ты можешь попробовать эту штуку через вагрант.
Только придется немного поднастроить приложение.
Там автоматический билд и по ошибкам всё должно быть понятно.
https://github.com/cookyii/cookyii
Не дошли пока руки донастроить приложения для вагранта (только первую версию виртуалки запили).

**Comment by rmrevin** [comment]
Я по своему опыту скажу, что в этом каркасе есть всё, для разработки scalable приложений разного уровня. Я не настаиваю на его использовании. Но рекомендую, т.к. для этого каркаса есть уже готовые, протестированые в продакшене решения.

**Comment by githubjeka** [comment]
Новости и статьи же будут на русском. Ещё можно сделать ленту из yiifeed. Также как сейчас для твиттера сделано, кстати и его не забыть.

**Comment by samdark** [comment]
Черновую версию сделал.

**Comment by loveorigami** [comment]
Будет ли подсветка кода в статьях?
У себя я делал через шорткоды на событиях, как в WP.
https://github.com/loveorigami/yii2-plugins-system

**Comment by githubjeka** [comment]
code в markdown легко посвечивается через js - https://highlightjs.org/

**Comment by samdark** [comment]
Будет. Хочу подсветить через https://github.com/scrivo/highlight.php.

**Comment by loveorigami** [comment]
@githubjeka через него я и подсвечиваю )

еще вот идея для списка статей и новостей. Чтоб после индексации из поиска попадать на нужную страницу со списком новостей, новости должны оставаться на статической странице.
А все новые добавляться на последующие. Иначе робот проиндексирует, на сайте за это вермя добавятся новые и все сдвинется...

Т.е. пагинация должна быть обратной.

У себя делал так
https://github.com/loveorigami/yii2-reversed-pagination

**Comment by githubjeka** [comment]
Так это сортировкой решается. Или вы о чём то другом?

**Comment by samdark** [comment]
Немного о другом. @loveorigami хабр, кстати, отказался от реверс-постранички.

**Comment by loveorigami** [comment]
@githubjeka да, о другом. Видимо, все зависит от количества записей. У меня, например, на сайте уже >50 000 записей http://new.loveorigami.info/world/. Каждый день добавляется по 20-30.
Робот зашел, проиндексировал 100 страницу (или пользователь на нее дал ссылку в форуме).
А через пару дней на 100 странице будут другие записи при прямой пагинации.

При обратной пагинации записи остаются на своей странице постоянно.
http://new.loveorigami.info/world/100 (и завтра, и через неделю содержимое этой страницы не изменится)

**Comment by githubjeka** [comment]
Понял.

15.08.15, Andrey<notifications@github.com> написал(а):
