### ISSUE TITLE
Авторизация через соцсети

### ISSUE THREAD

**Issue by samdark** [samdark/yiiframework-ru#48]
- [ ] Кнопки в форме логина должны работать как авторизация через соцсети
- [ ] Возможность в профиле привязать соцсеть

**Comment by githubjeka** [comment]
В твиттере не возвращается email, а для создания пользователя требуется email. Как быть?

**Comment by samdark** [comment]
Не требовать email. См. https://github.com/samdark/yiifeed.

Кстати, от twitter можно получать email, если сильно попросить.

**Comment by lavrentiev** [comment]
Думаю можно закрывать.

**Comment by githubjeka** [comment]
https://github.com/samdark/yiiframework-ru/pull/50
https://github.com/samdark/yiiframework-ru/pull/49
