### ISSUE TITLE
Кнопка logout.

### ISSUE THREAD

**Issue by githubjeka** [samdark/yiiframework-ru#52]
Не нашёл :)

**Comment by lavrentiev** [comment]
ctrl+shift+i и там куки тереть )

**Comment by githubjeka** [comment]
Так и сделал, впринципе меня это устраивает, а вот остальных думаю нет :)

**Comment by lavrentiev** [comment]
я предлагаю при нажатие на фото юзера в меню, открывать небольшое окошко dropdown и там выйти, редактировать и т.д....

**Comment by samdark** [comment]
Да, можно и так.

**Comment by lavrentiev** [comment]
А сергей сделает нам это сея чудо ? а то из меня дизайнер ...

**Comment by githubjeka** [comment]
Мы обсуждали с Сергеем это выезжающее меню на заре дизайна. Было решено отказаться. Кнопку выход можно сделать в профиле. Т.е нажимаем на аватару  -попадаем в профиль и там есть эта кнопка.

**Comment by samdark** [comment]
Да, тоже норм.

**Comment by samdark** [comment]
Давайте так.

**Comment by Carsak** [comment]
> ctrl+shift+i и там куки тереть )

Зачем так. F12 быстрее :smiley:
