### ISSUE TITLE
Запоминать сокрытие достоинства YII

### ISSUE THREAD

**Issue by lavrentiev** [samdark/yiiframework-ru#58]
Запоминать сокрытие достоинства YII при нажатие на крестик на главной странице.

**Comment by Carsak** [comment]
Извините, не удержался.
сокрытие достоинства
Когда прочитал заголовок даже удивился.
Выдохнул только когда прочитал полную новость.
Может правильней, "закрытие окна с преимуществами"

**Comment by samdark** [comment]
Так забавней :)

**Comment by lavrentiev** [comment]
@Carsak Достоинство круче звучит )))
