### ISSUE TITLE
Разработать концепцию дизайна

### ISSUE THREAD

**Issue by rmrevin** [samdark/yiiframework-ru#6]
Что с дизайном делать будем?
Я предлагаю купить темку на wrapbootstrap.com и адаптировать её под фирменный стиль.

**Comment by samdark** [comment]
Предлагаю для начала не заморачиваться и сделать с дефолтной bootstrap-темой. А то застрянем.

**Comment by RSalo** [comment]
@rmrevin я предлагаю сначала спросить у сообщества. ведь явно есть дизайнеры с доброй душой. покупать что-то, крайний случай...

**Comment by rmrevin** [comment]
@samdark с готовой темой не вижу проблем. Тот же бутстрап, но не так убого выглядищий.
@RSalo как раз с разработкой дизайна мы можем застрять. На шаблон я уж 15 долларов найду в своем бюджете =)

По поводу шаблона я не предлагаю подбирать супер крутой дизайн. Просто подобрать шаблон, где светлые тона и много свободного пространства (это моё представление о лёгком дизайне).

**Comment by samdark** [comment]
@rmrevin http://bootstraptaste.com/theme/moderna/index.html пойдёт?

**Comment by rmrevin** [comment]
@samdark вполне. Только у меня в хроме анимация глючит. Но в целом - ок.

**Comment by RSalo** [comment]
тогда уже лучше http://bootstraptaste.com/theme/appland/index.html

**Comment by rmrevin** [comment]
@RSalo предыдущий вариант мне нравится больше. Он больше похож на yiigist.com цветовой гаммой  =)

**Comment by RSalo** [comment]
@rmrevin согласен, надо ставить твой вариант. у моего варианта просто кнопки как в yiiframework.com сайта. ностальгия...

**Comment by samdark** [comment]
Вот и замечательно. Платить ничего не надо.

**Comment by rmrevin** [comment]
выбрали http://bootstraptaste.com/free-bootstrap-template-corporate-moderna/
