### ISSUE TITLE
Хранить "Дату" не в unixtime, а в DATETIME

### ISSUE THREAD

**Issue by Carsak** [samdark/yiiframework-ru#61]
Почему дата в таблице пользователей хранится в интегере?
Ведь это считается дурным тоном в прогаммировании. 
Предлагаю перевести эти даты в datetime.
[скриншот](http://joxi.ru/v29dMPnfGkpDWm)

**Comment by lavrentiev** [comment]
Зачем ?

**Comment by githubjeka** [comment]
@Carsak 8 байт хранить против 4 и без учёта часового пояса - сомнительное предложение. Читабильность из таблицы в данном случае нам не нужна, использовать ништяковые sql функции для работы с Datetime тоже не надо, а ещё нам может понадобится в будущем показывать даты с учётом часового пояса конкретного пользователя.

**Comment by Carsak** [comment]
Против таких аргументов трудно спорить.
