### ISSUE TITLE
NotificationFlash 

### ISSUE THREAD

**Issue by loveorigami** [samdark/yiiframework-ru#64]
Для удобной работы с flash сообщениями предлагаю использовать модуль
https://github.com/loveorigami/yii2-notification-wrapper

Принцип работы такой же, как и тут
https://github.com/samdark/yiiframework-ru/blob/326b267789459b7e300fe51e09f42aee858b7be3/frontend/views/layouts/main.php#L94

т.к. я его использую в качестве одного из виджетов

особенностью является вывод флеш сообщений после ajax запросов

Например - отобразить сообщение тут
https://github.com/samdark/yiiframework-ru/blob/6877c121f88f00a27be8d86b2e3a34782aa5ea66/frontend/controllers/QaController.php#L244

( добавлено или удалено из избранного.)
- появляется возможность поменять библиотеку для флеш сообщений, не привязываясь к js
  (например, вместо Toastr установить Noty)

**Comment by loveorigami** [comment]
сделал второй релиз.
Отказался от сторонних виджетов, чтоб не тянуть в зависимость все пакеты.
Теперь ставим добавляем нужный bower и используем аналогичный Layer.

**Comment by lavrentiev** [comment]
Ну да согласен, даже попробовал, реализация очень хорошая.
