### ISSUE TITLE
Сделать хук GitHub на обновления кукбука 1.1

### ISSUE THREAD

**Issue by samdark** [samdark/yiiframework-ru#72]
```
git submodule foreach git pull origin master
```

https://github.com/samdark/yiiframework_ru_cookbook/settings/hooks

**Comment by Carsak** [comment]
Ссылка https://github.com/samdark/yiiframework_ru_cookbook/settings/hooks отдает 404

**Comment by rugabarbo** [comment]
@Carsak, потому что у Вас доступа нет к хукам.

**Comment by samdark** [comment]
В принципе, оно не так важно. Кукбук по 1.1 уже давно не обновлялся.
