### ISSUE TITLE
Проекты на Yii

### ISSUE THREAD

**Issue by samdark** [samdark/yiiframework-ru#74]
Допилить, включить.

**Comment by dignityinside** [comment]
+1

**Comment by samdark** [comment]
https://github.com/yiisoft-contrib/yiiframework.com/issues/185

**Comment by samdark** [comment]
Решил не допиливать, а сделать отдельный проект + сослаться на него с yiiframework.ru и yiiframework.com.

**Comment by rugabarbo** [comment]
В этом случае наверно нужно выпилить из этого репозитория весь код, связанный с проектами. В том числе в БД есть две таблицы...

**Comment by rugabarbo** [comment]
Issue по выпиливанию: #113

**Comment by samdark** [comment]
http://yiipowered.com/ru/

**Comment by dignityinside** [comment]
Добавил два свои проекта :) Немного не удобно, что скриншот пришлось самому делать и загружать и тэги я бы сделал как на gostash.

**Comment by samdark** [comment]
Да, там ещё надо поработать на возможностями.
