### ISSUE TITLE
Ошибка восстановления пароля

### ISSUE THREAD

**Issue by voskobovich** [samdark/yiiframework-ru#75]
Пробую восстановить пароль, и получаю "Возникла внутренняя ошибка сервера."
Не уверен, что мой емейл есть в базе, так что, возможно, ошибка в этом.

**Comment by samdark** [comment]
https://github.com/samdark/yiiframework-ru/issues/70

**Comment by voskobovich** [comment]
Если бы это было связано с неприходящей почтой, то я не получал бы ошибки на фронт.
То есть я бы отправлял форму  мне бы писало что все ОК, но письмо не приходило бы.
А здесь 500-я ошибка вероятнее всего.

**Comment by samdark** [comment]
Да, скорее всего. Проверю.
