### ISSUE TITLE
Нужна корректная вёрстка search блока.

### ISSUE THREAD

**Issue by githubjeka** [samdark/yiiframework-ru#80]
![image](https://cloud.githubusercontent.com/assets/874234/20881204/49750cd2-baec-11e6-946a-545aa3316996.png)
согласно шаблону-дизайну https://github.com/eshill/Yiiframework.ru/blob/master/Preview/User_profile.png

**Comment by githubjeka** [comment]
Sergei Khilkov @eshill 13:31
Там инпут поиска съехал 
и не увеличивается при фокусе.
http://eshill.ru/_preview/yii/article_view.html
тут как должно быть

**Comment by alexantr** [comment]
У инпута класса `page-search` не хватает. С ним все становится на свои места.

**Comment by samdark** [comment]
https://github.com/samdark/yiiframework-ru/commit/689cfa7731d7fa8b4e533293c483565e702581ff
