### ISSUE TITLE
Улучшение перехода между страницами с новостями.

### ISSUE THREAD

**Issue by githubjeka** [samdark/yiiframework-ru#81]
На главной при переходе на предыдущие страницы постов, перезагружается страница с прыжком в самый вверх страницы.

Нужно добавить якорь к началу блока постов и добавить его к пагинации. Было бы здорово добавить плавный скролл к якорю.

**Comment by graid2030** [comment]
Я бы лучше убирал шапку у 1+ страниц

**Comment by githubjeka** [comment]
Хм, хорошее предложение.

**Comment by rugabarbo** [comment]
Неясно, что значит "убрать шапку"? Сужать и прилеплять её к потолку как здесь http://yiiframework.ru/users во время прокрутки?

**Comment by graid2030** [comment]
Убрать в принципе блок с "Русскоязычное сообщество Yii" + описание. Очевидно что при перелистывании страниц основное внимание должно быть на контент. А сейчас требуется солидно так до него пролистывать.

**Comment by samdark** [comment]
А что имеется ввиду под `1+`  страницами?

**Comment by samdark** [comment]
Так нет вроде блока нигде кроме как на главной... http://yiiframework.ru/news/127/yii-2-inspections-dla-intellij-idea

**Comment by graid2030** [comment]
Об этом речь http://yiiframework.ru/news?page=2&per-page=10

**Comment by samdark** [comment]
Это, по сути, главная.

**Comment by rugabarbo** [comment]
Может лучше сделать кнопку "Показать ещё", а ниже пагинацию? Как на маркете: https://market.yandex.ru/catalog/55316

**Comment by samdark** [comment]
Не, не надо.

**Comment by rugabarbo** [comment]
Если начиная со второй страницы новостей убирать промо-часть шапки, будет выглядеть так:

![17 01 21-16 34 30](https://cloud.githubusercontent.com/assets/6429469/22174794/9eb3b880-dff7-11e6-885d-e0d8497d6581.png)

По-моему, нормально. И скролить в этом случае ничего не нужно. **При этом на первой странице (на главной) всё останется как есть без изменений.**

**Comment by samdark** [comment]
Нормально, только, возможно, лучше взять layout с шапкой от страниц постов? http://yiiframework.ru/news/127/yii-2-inspections-dla-intellij-idea

**Comment by rugabarbo** [comment]
> Нормально, только, возможно, лучше взять layout с шапкой от страниц постов? 

Попробовал. Можешь посмотреть в PR: колонку твитов перенёс в представление списка постов, а список постов оборачиваю в макет 'common' (если page >= 2) и в макет 'front' (если page < 2).

При этом внёс пару CSS-фиксов, чтобы новости с твитами нормально отображались под макетом 'common'.

**Comment by samdark** [comment]
Проверил. Смёржил.

**Comment by samdark** [comment]
Отлично вышло.
