### ISSUE TITLE
После подключения аккаунта GitHub пользователя перебрасывает на главную

### ISSUE THREAD

**Issue by alexantr** [samdark/yiiframework-ru#88]
На странице [редактирования профиля](http://yiiframework.ru/user/edit) после привязки аккаунта окошко GiHub закрывается и пользователя перебрасывает на главную вместо того, чтобы оставить его там же.

**Comment by rugabarbo** [comment]
@samdark, как можно на локалке сконфигурировать authclient?
В продакшене, насколько я понимаю, заполнен конфиг https://github.com/samdark/yiiframework-ru/blob/master/config/system/authclients.php 
А на локальной машине как конфигурируешь для разработки?

**Comment by samdark** [comment]
1. Регистрируется на свой аккаунт приложение GitHub. Callback должен вести на локальный сайт.
2. Тот конфиг копируется в `/config/authclients.php`. Заполняется реальными данными из пункта 1.
