### ISSUE TITLE
Добавить больше SEO-возможностей

### ISSUE THREAD

**Issue by alexantr** [samdark/yiiframework-ru#89]
Например, у главной заголовок "Посты". Нет мета-описания. Также были бы полезны OpenGraph-теги для публикации ссылок в соц. сетях.

**Comment by rugabarbo** [comment]
"Больше возможностей" - это очень абстрактная формулировка. Кто мог бы составить более точный список необходимых SEO-правок?

**Comment by samdark** [comment]
- [ ] Осмысленные title на каждую страницу.
- [ ] Осмысленные description.
- [ ] Теги авторства должны соответствовать авторам постов.
- [ ] Теги для карточек Twitter и Facebook.

**Comment by alexantr** [comment]
Необходимо редактирование:
* *заголовка страницы* для `<title>`, `<meta property="og:title">` и `<meta name="twitter:title">`
* *описания страницы* для `<meta name="description">`, `<meta property="og:description">` и `<meta name="twitter:description">`
* *изображения страницы* для `<meta property="og:image">` и `<meta name="twitter:image">` - используется как превью при расшаривании в соц. сетях.

OG-теги для соц. сетей:
```html
<meta property="og:type" content="website"> <!-- для отдельных статей content="article" -->
<meta property="og:site_name" content="название сайта">
<meta property="og:url" content="URL текущей страницы">
<meta property="og:title" content="Заголовок текущей страницы">
<meta property="og:description" content="Описание текущей страницы">
<meta property="og:image" content="URL картинки">
```
[Описание на Фейсбуке](https://developers.facebook.com/docs/sharing/webmasters), [полное описание протокола Open Graph](http://ruogp.me/)

Теги для Твиттера:
```html
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@yiiframework_ru">
<meta name="twitter:title" content="Заголовок текущей страницы">
<meta name="twitter:description" content="Описание текущей страницы">
<meta name="twitter:image" content="URL картинки">
```
[Описание в Твиттере](https://dev.twitter.com/cards/types/summary-large-image)

**Comment by rugabarbo** [comment]
Нужно вдумчиво поревьюировать всё это дело, а потом также вдумчиво потестировать расшаривание в соцсетях после выкладки...

**Comment by alexantr** [comment]
Для тестирования тегов у фэйсбука есть [дебаггер](https://developers.facebook.com/tools/debug/) и [валидатор](https://cards-dev.twitter.com/validator) у твиттера.
