### ISSUE TITLE
Сайты на Yii

### ISSUE THREAD

**Issue by samdark** [samdark/yiiframework-ru#9]
Галерея сайтов на Yii.

- Название.
- Описание.
- Скриншоты.
- Ссылка на студию / сайт разработчика.

**Comment by lavrentiev** [comment]
Можно добавить версию используемой Yii и ссылку чтобы пожаловаться (типа вранье или это не Yii)

**Comment by RSalo** [comment]
@lavrentiev тогда уже надо, чтобы репозитории свои открывали с сайтами=) по другому особо не сможешь доказать yii это или нет

**Comment by lavrentiev** [comment]
@RSalo я про кнопочку имел ввиду что вдруг там какое нить dle на сайте или битрикс или еще какое нить. а версию пусть какую хочет указывает автор.

**Comment by RSalo** [comment]
@lavrentiev у меня есть более глубокая задумка. чтобы можно было сайты постить в галерею, надо поставить специальное расширение, которое будет собирать и отправлять основную инфу о сайте. потом эту же инфу можно использовать в расчетах для рейтинга. я не знаю, может быть это будет слишком сложно в реализации и никому не надо...

**Comment by lavrentiev** [comment]
@RSalo ага тока сделаешь так и сразу пойдут разговоры о вселенском заговоре.

**Comment by samdark** [comment]
Не, так делать не стоит :)

**Comment by samdark** [comment]
```
project
---------
id
title
link
body
user_id
status
created_at
updated_at

project_image
-------------------

id
project_id
title
body
```

**Comment by githubjeka** [comment]
Сделал набросок - ветка [**project**](https://github.com/samdark/yiiframework-ru/tree/project), кто чем может помогайте ;)
