### ISSUE TITLE
Открывать ссылки на форум в отдельном окне

### ISSUE THREAD

**Issue by rugabarbo** [samdark/yiiframework-ru#93]
Недавно на форуме главной страницей сделали главную форума: http://yiiframework.ru/forum/viewtopic.php?t=42007#p207556

Мне кажется, что теперь было бы более логичным на сайте открывать ссылки форума в новом окне (target => blank), потому что форум достаточно обособлен от сайта.

Что думаете?

**Comment by samdark** [comment]
Да, можно.
