### ISSUE TITLE
Почему пагинация новостей (постов) завязана на GET-параметры?

### ISSUE THREAD

**Issue by rugabarbo** [samdark/yiiframework-ru#98]
Имеем URL-ы вида **(1)**: http://yiiframework.ru/news?page=2&per-page=10

Можно ведь сделать более удобоваримый вид **(2)**: http://yiiframework.ru/news/2

Подскажите мне, вид **(1)** - это обратная совместимость с чем-то прошедшим (например, со старым сайтом)? Или же вполне можно переключиться на **(2)** без всяких проблем?

**Comment by samdark** [comment]
Можно и переключиться.

**Comment by samdark** [comment]
Можно и переключиться.

**Comment by RSalo** [comment]
@samdark у нас походу новости в таком виде урла показываются http://yiiframework.ru/news/какое-то-название-новости
Лучше всего уже так сделать http://yiiframework.ru/news/page/2, чтобы пагинация и названия новостей в кучу не мешалось...

**Comment by rugabarbo** [comment]
slug из латиницы состоит, а номер страницы из цифр - они не смешаются.

**Comment by samdark** [comment]
ОК.
