### ISSUE TITLE
Автокомплит в IDE

### ISSUE THREAD

**Issue by rugabarbo** [samdark/yiiframework-ru#99]
Начиная с этой строчки https://github.com/samdark/yiiframework-ru/blob/master/views/layouts/main.php#L39 PhpStorm показывает мне такую картинку:

![17 01 15-13 12 36](https://cloud.githubusercontent.com/assets/6429469/21961774/67779580-db24-11e6-8c72-9c90751a7590.png)

Как мы все знаем, эту проблему можно решить размещением файлика **autocomplete.php** в корне проекта. Стоит ли это делать? Или может быть вы решаете проблему автокомплита IDE-плагинами?

**Comment by samdark** [comment]
Решить можно вот так:

```php
/** @var User $user */
$user = Yii::$app->user->identity;
```

**Comment by rugabarbo** [comment]
Саша, я про решение в целом (уровня проекта, а не уровня одного участка кода).

Например, тебе будет мешать этот автокомплит-файл?

**Comment by samdark** [comment]
Нет, не будет.
